package pipeline

import (
	"testing"
)

func TestParseGoSum(t *testing.T) {
	content := "github.com/stretchr/testify v1.8.4 h1:abc123=\ngithub.com/stretchr/testify v1.8.4/go.mod h1:abc123=\ngolang.org/x/sync v0.5.0 h1:def456=\ngolang.org/x/sync v0.5.0/go.mod h1:def456=\n"
	deps := parseGoSum(content)
	if len(deps) != 2 {
		t.Fatalf("expected 2 deps, got %d: %v", len(deps), deps)
	}
	// Verify both packages are present (order may vary due to map iteration)
	found := make(map[string]string)
	for _, d := range deps {
		found[d.Name] = d.Version
	}
	if v, ok := found["github.com/stretchr/testify"]; !ok || v != "v1.8.4" {
		t.Errorf("expected testify v1.8.4, got %q", v)
	}
	if v, ok := found["golang.org/x/sync"]; !ok || v != "v0.5.0" {
		t.Errorf("expected sync v0.5.0, got %q", v)
	}
}

func TestParseRequirementsLock(t *testing.T) {
	content := "# autogenerated\nboto3==1.34.0\n    # via -r requirements.in\nbotocore==1.34.0\n    # via boto3\nhttpx==0.27.0\n"
	deps := parseRequirementsLock(content)
	if len(deps) != 3 {
		t.Fatalf("expected 3 deps, got %d: %v", len(deps), deps)
	}
	expected := map[string]string{
		"boto3":    "1.34.0",
		"botocore": "1.34.0",
		"httpx":    "0.27.0",
	}
	for _, d := range deps {
		if v, ok := expected[d.Name]; !ok {
			t.Errorf("unexpected dep: %s", d.Name)
		} else if d.Version != v {
			t.Errorf("dep %s: expected version %s, got %s", d.Name, v, d.Version)
		}
	}
}

func TestParsePackageLockJSON(t *testing.T) {
	content := `{"name":"app","lockfileVersion":3,"packages":{"":{"name":"app","version":"1.0.0"},"node_modules/express":{"version":"4.18.2"},"node_modules/lodash":{"version":"4.17.21"}}}`
	deps := parsePackageLockJSON(content)
	if len(deps) != 2 {
		t.Fatalf("expected 2 deps (excluding root), got %d: %v", len(deps), deps)
	}
	found := make(map[string]string)
	for _, d := range deps {
		found[d.Name] = d.Version
	}
	if v, ok := found["express"]; !ok || v != "4.18.2" {
		t.Errorf("expected express 4.18.2, got %q", v)
	}
	if v, ok := found["lodash"]; !ok || v != "4.17.21" {
		t.Errorf("expected lodash 4.17.21, got %q", v)
	}
}

func TestParseGoSumEmpty(t *testing.T) {
	deps := parseGoSum("")
	if len(deps) != 0 {
		t.Errorf("expected 0 deps for empty content, got %d", len(deps))
	}
}

func TestParseRequirementsLockComments(t *testing.T) {
	content := "# comment\n    # indented comment\n\nrequests==2.31.0\n"
	deps := parseRequirementsLock(content)
	if len(deps) != 1 {
		t.Errorf("expected 1 dep, got %d", len(deps))
	}
	if len(deps) == 1 {
		if deps[0].Name != "requests" || deps[0].Version != "2.31.0" {
			t.Errorf("expected requests==2.31.0, got %s==%s", deps[0].Name, deps[0].Version)
		}
	}
}

func TestParsePackageLockJSONScopedPackage(t *testing.T) {
	content := `{"packages":{"":{"name":"app","version":"1.0.0"},"node_modules/@babel/core":{"version":"7.24.0"}}}`
	deps := parsePackageLockJSON(content)
	if len(deps) != 1 {
		t.Fatalf("expected 1 dep, got %d: %v", len(deps), deps)
	}
	if deps[0].Name != "@babel/core" || deps[0].Version != "7.24.0" {
		t.Errorf("expected @babel/core 7.24.0, got %s %s", deps[0].Name, deps[0].Version)
	}
}

func TestParseRequirementsLockWithMarkers(t *testing.T) {
	content := "cffi==1.16.0 ; python_implementation != 'PyPy'\ncryptography==42.0.0\n"
	deps := parseRequirementsLock(content)
	if len(deps) != 2 {
		t.Fatalf("expected 2 deps, got %d: %v", len(deps), deps)
	}
	found := make(map[string]string)
	for _, d := range deps {
		found[d.Name] = d.Version
	}
	if v := found["cffi"]; v != "1.16.0" {
		t.Errorf("expected cffi 1.16.0, got %q (marker should be stripped)", v)
	}
}

func TestParsePackageLockJSONInvalid(t *testing.T) {
	deps := parsePackageLockJSON("not json")
	if len(deps) != 0 {
		t.Errorf("expected 0 deps for invalid JSON, got %d", len(deps))
	}
}

func TestParseGoSumMalformedLines(t *testing.T) {
	content := "just-a-name\n\ngithub.com/pkg/errors v0.9.1 h1:abc=\n"
	deps := parseGoSum(content)
	if len(deps) != 1 {
		t.Fatalf("expected 1 dep (malformed line skipped), got %d: %v", len(deps), deps)
	}
	if deps[0].Name != "github.com/pkg/errors" {
		t.Errorf("expected github.com/pkg/errors, got %s", deps[0].Name)
	}
}
