package tools

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"strings"

	"github.com/DeusData/codebase-memory-mcp/internal/store"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

// ReportFileName is the name of the markdown report written to the repo root
// by generateOrientationReport. Callers (e.g. the PreToolUse hook shell script)
// reference this name, so it is exported for cross-language consistency.
const ReportFileName = "ARCHITECTURE_REPORT.md"

// orientationReportResult is the structured return value of generate_report.
type orientationReportResult struct {
	Project  string         `json:"project"`
	Path     string         `json:"path"`
	Nodes    int            `json:"nodes"`
	Edges    int            `json:"edges"`
	Bytes    int            `json:"bytes"`
	GodNodes int            `json:"god_nodes"`
	Clusters int            `json:"clusters"`
	Routes   int            `json:"routes"`
	Metadata map[string]any `json:"_metadata,omitempty"`
}

// handleGenerateReport is the generate_report MCP tool handler. Regenerates
// ARCHITECTURE_REPORT.md without re-indexing — useful when the user wants a
// fresh report after manual edits to the graph, or when index_repository was
// called on an older binary that did not auto-generate the report.
func (s *Server) handleGenerateReport(_ context.Context, req *mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	args, err := parseArgs(req)
	if err != nil {
		return errResult(err.Error()), nil
	}

	projectArg := getStringArg(args, "project")
	project := s.resolveProjectName(projectArg)
	if project == "" {
		return errResult("project is required (pass `project` explicitly or call from a session with a resolved project)"), nil
	}

	result, err := s.generateOrientationReport(project)
	if err != nil {
		return errResult(fmt.Sprintf("generate report: %v", err)), nil
	}
	result.Metadata = s.stdWriteToolMetadata(ActionOutcomeCreated)

	body, _ := json.MarshalIndent(result, "", "  ")
	return &mcp.CallToolResult{
		Content: []mcp.Content{&mcp.TextContent{Text: string(body)}},
	}, nil
}

// generateOrientationReport builds ARCHITECTURE_REPORT.md for a project and
// writes it to the repo root. The report is a one-page orientation doc
// intended for coding assistants to read BEFORE running Glob/Grep on an
// unfamiliar codebase; a PreToolUse hook (installed via the `install`
// subcommand) nudges the agent toward this file when file-exploration tools
// fire.
func (s *Server) generateOrientationReport(projectName string) (*orientationReportResult, error) {
	st, err := s.router.ForProject(projectName)
	if err != nil {
		return nil, fmt.Errorf("resolve store: %w", err)
	}

	projs, err := st.ListProjects()
	if err != nil {
		return nil, fmt.Errorf("list projects: %w", err)
	}
	var rootPath string
	for _, p := range projs {
		if p.Name == projectName {
			rootPath = p.RootPath
			break
		}
	}
	if rootPath == "" {
		return nil, fmt.Errorf("project %q has no root_path — reindex with index_repository first", projectName)
	}
	if info, statErr := os.Stat(rootPath); statErr != nil || !info.IsDir() {
		return nil, fmt.Errorf("root_path for %q is not a directory: %s", projectName, rootPath)
	}

	arch, err := st.GetArchitecture(projectName, nil)
	if err != nil {
		return nil, fmt.Errorf("get architecture: %w", err)
	}

	nodeCount, _ := st.CountNodes(projectName)
	edgeCount, _ := st.CountEdges(projectName)

	md := renderOrientationReport(projectName, nodeCount, edgeCount, arch)

	outPath := filepath.Join(rootPath, ReportFileName)
	if err := os.WriteFile(outPath, []byte(md), 0o644); err != nil {
		return nil, fmt.Errorf("write report: %w", err)
	}

	godCount := 0
	if arch != nil {
		godCount = len(arch.Hotspots)
	}
	clusterCount := 0
	routeCount := 0
	if arch != nil {
		clusterCount = len(arch.Clusters)
		routeCount = len(arch.Routes)
	}

	slog.Info("report.write",
		"project", projectName,
		"path", outPath,
		"bytes", len(md),
		"gods", godCount,
		"clusters", clusterCount,
		"routes", routeCount)

	return &orientationReportResult{
		Project:  projectName,
		Path:     outPath,
		Nodes:    nodeCount,
		Edges:    edgeCount,
		Bytes:    len(md),
		GodNodes: godCount,
		Clusters: clusterCount,
		Routes:   routeCount,
	}, nil
}

// renderOrientationReport assembles the markdown. Split out from
// generateOrientationReport so tests can exercise it with a fixture
// ArchitectureInfo without touching disk.
func renderOrientationReport(name string, nodeCount, edgeCount int, arch *store.ArchitectureInfo) string {
	var sb strings.Builder

	fmt.Fprintf(&sb, "# %s\n\n", name)
	sb.WriteString("_Architecture orientation report, auto-generated by `codebase-memory-mcp` ")
	sb.WriteString("from the indexed graph. Regenerated on every `index_repository`; ")
	sb.WriteString("regenerate manually with the `generate_report` MCP tool._\n\n")
	fmt.Fprintf(&sb, "- **Graph**: %d nodes, %d edges\n", nodeCount, edgeCount)
	if arch != nil && len(arch.Languages) > 0 {
		parts := make([]string, 0, minInt(5, len(arch.Languages)))
		for _, l := range arch.Languages[:minInt(5, len(arch.Languages))] {
			parts = append(parts, fmt.Sprintf("%s (%d)", l.Language, l.FileCount))
		}
		fmt.Fprintf(&sb, "- **Languages**: %s\n", strings.Join(parts, ", "))
	}
	sb.WriteString("\n")

	sb.WriteString("## Start Here\n\n")
	sb.WriteString("If you are a coding assistant orienting to this repo, read this report ")
	sb.WriteString("**before** running `Glob`/`Grep` on the files. It tells you the ")
	sb.WriteString("high-degree functions (god nodes), the natural communities of code, ")
	sb.WriteString("and the cross-package boundaries. Drill in with `query_graph`, ")
	sb.WriteString("`trace_call_path`, or `get_relevant_context` from the code-graph MCP.\n\n")

	if arch != nil && len(arch.Hotspots) > 0 {
		sb.WriteString("## God Nodes (Most-Called Functions)\n\n")
		sb.WriteString("Highest fan-in in the CALLS graph — many callers depend on these. ")
		sb.WriteString("Changing them has the largest blast radius.\n\n")
		sb.WriteString("| Function | Qualified Name | Fan-in |\n|---|---|--:|\n")
		for _, h := range arch.Hotspots[:minInt(20, len(arch.Hotspots))] {
			fmt.Fprintf(&sb, "| `%s` | `%s` | %d |\n",
				escapeMD(h.Name), escapeMD(h.QualifiedName), h.FanIn)
		}
		sb.WriteString("\n")
	}

	if arch != nil && len(arch.Clusters) > 0 {
		sb.WriteString("## Communities (Cohesive Modules)\n\n")
		sb.WriteString("Louvain clustering on the CALLS graph. `cohesion` = intra-cluster ")
		sb.WriteString("edges / theoretically-possible edges (higher = tighter module).\n\n")
		sb.WriteString("| # | Label | Members | Cohesion | Top Nodes |\n|--:|---|--:|--:|---|\n")
		for i, c := range arch.Clusters[:minInt(10, len(arch.Clusters))] {
			top := c.TopNodes
			if len(top) > 3 {
				top = top[:3]
			}
			fmt.Fprintf(&sb, "| %d | `%s` | %d | %.2f | %s |\n",
				i+1, escapeMD(c.Label), c.Members, c.Cohesion,
				escapeMD(strings.Join(top, ", ")))
		}
		sb.WriteString("\n")
	}

	if arch != nil && len(arch.Boundaries) > 0 {
		sb.WriteString("## Cross-Package Boundaries\n\n")
		sb.WriteString("Call traffic between packages. High-traffic pairs are likely implicit ")
		sb.WriteString("module seams that may benefit from a named interface.\n\n")
		sb.WriteString("| From | → | To | Calls |\n|---|:-:|---|--:|\n")
		for _, b := range arch.Boundaries[:minInt(15, len(arch.Boundaries))] {
			fmt.Fprintf(&sb, "| `%s` | → | `%s` | %d |\n",
				escapeMD(b.From), escapeMD(b.To), b.CallCount)
		}
		sb.WriteString("\n")
	}

	if arch != nil && (len(arch.Routes) > 0 || len(arch.EntryPoints) > 0) {
		sb.WriteString("## Entry Points\n\n")
		if len(arch.Routes) > 0 {
			sb.WriteString("### HTTP Routes\n\n")
			sb.WriteString("| Method | Path | Handler |\n|---|---|---|\n")
			for _, r := range arch.Routes[:minInt(15, len(arch.Routes))] {
				method := r.Method
				if method == "" {
					method = "—"
				}
				fmt.Fprintf(&sb, "| `%s` | `%s` | `%s` |\n",
					escapeMD(method), escapeMD(r.Path), escapeMD(r.Handler))
			}
			sb.WriteString("\n")
		}
		if len(arch.EntryPoints) > 0 {
			sb.WriteString("### Process Entry Points\n\n")
			for _, ep := range arch.EntryPoints[:minInt(10, len(arch.EntryPoints))] {
				file := ep.File
				if file == "" {
					file = "—"
				}
				fmt.Fprintf(&sb, "- `%s` — `%s` (`%s`)\n",
					escapeMD(ep.Name), escapeMD(ep.QualifiedName), escapeMD(file))
			}
			sb.WriteString("\n")
		}
	}

	sb.WriteString("## Suggested Questions\n\n")
	sb.WriteString("The graph is uniquely positioned to answer these. Prefer `query_graph` / ")
	sb.WriteString("`trace_call_path` / `get_relevant_context` over raw file search.\n\n")
	qn := 0
	emit := func(line string) {
		qn++
		fmt.Fprintf(&sb, "%d. %s\n", qn, line)
	}
	if arch != nil && len(arch.Hotspots) > 0 {
		top := arch.Hotspots[0].Name
		emit(fmt.Sprintf("**Who calls `%s`?** — `trace_call_path(function_name=\"%s\", direction=\"inbound\", depth=2)`",
			escapeMD(top), top))
	}
	if arch != nil && len(arch.Clusters) >= 2 {
		a := arch.Clusters[0].Label
		b := arch.Clusters[1].Label
		emit(fmt.Sprintf("**How does the `%s` community connect to `%s`?** — `query_graph(\"MATCH path=(x)-[:CALLS*1..3]->(y) WHERE x.package='%s' AND y.package='%s' RETURN path LIMIT 10\")`",
			escapeMD(a), escapeMD(b), a, b))
	}
	if arch != nil && len(arch.Routes) > 0 {
		r := arch.Routes[0]
		emit(fmt.Sprintf("**What does the `%s %s` handler touch?** — `trace_call_path(function_name=\"%s\", direction=\"outbound\", depth=3)`",
			escapeMD(r.Method), escapeMD(r.Path), r.Handler))
	}
	emit("**What are the dead-code candidates?** — `search_graph(label=\"Function\", relationship=\"CALLS\", direction=\"inbound\", max_degree=0, exclude_entry_points=true)`")
	emit("**What is the blast radius of changing a file?** — `detect_changes(scope=\"file\", path=\"<path>\")`")

	sb.WriteString("\n---\n\n")
	sb.WriteString("_Report refreshes on every `index_repository` run. For manual regeneration: ")
	sb.WriteString("call the `generate_report` MCP tool. This file is safe to commit to git so ")
	sb.WriteString("teammates get an instant orientation after `git pull`._\n")

	return sb.String()
}

// escapeMD replaces Markdown-significant characters in identifier-like strings
// so they don't break table cells. Scope is narrow because most content here
// is already-trusted identifiers from the indexed graph.
func escapeMD(s string) string {
	s = strings.ReplaceAll(s, "|", "\\|")
	s = strings.ReplaceAll(s, "\n", " ")
	return s
}

func minInt(a, b int) int {
	if a < b {
		return a
	}
	return b
}
